# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  pathtosolution: 'PizzaBoxWebApp/'
  pathtoproject: 'PizzaBoxWebApp/PizzaBoxWebApp.Web'
  pathtotest: 'PizzaBoxWebApp/PizzaBoxWebApp.Test'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud Connection 1'
    organization: '$(SonarOrganization)'
    scannerMode: 'MSBuild'
    projectKey: '$(SonarProjectKey)'
    projectName: '$(SonarProjectName)'
    extraProperties: |
      sonar.cs.opencover.reportsPaths="$(Build.ArtifactStagingDirectory)/coverage/*"
      sonar.cs.vstest.reportsPaths="$(Build.ArtifactStagingDirectory)/test/*.trx"
      sonar.exclusions=**/wwwroot/lib/**/*
- script: 
    dotnet build --configuration $(buildConfiguration)
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test
    --configuration $(buildConfiguration)
    --logger trx
    --no-build
    --results-directory $(Build.ArtifactStagingDirectory)/PizzaBoxWebApp.Test/
    /p:CollectCoverage=true
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet test'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
    
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '*.trx'
    searchFolder: '$(Build.ArtifactStagingDirectory)/PizzaBoxWebApp.Test'
  displayName: 'Publish test results'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: --configuration $(buildConfiguration)
    publishWebProjects: true
    zipAfterPublish: true
    workingDirectory: '$(pathtosolution)'
  displayName: 'dotnet publish + zip'
####--- CI END

## CDelivery Start taking artifact as an input
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(df200939-e69d-451d-a8b5-48d9c18a706b)'
    appType: 'webAppLinux'
    appName: 'ezpizza'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'